language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
branches:
  only:
    - develop
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
notifications:
  email: sugama@jamadam.com
