#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename 'dirname';
use File::Spec;

use Data::Dumper;
use Getopt::Long 'GetOptionsFromArray';

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '../extlib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '../lib';

# Check if Mojo is installed
eval 'use Mojolicious::Commands';
die <<EOF if $@;
It looks like you don't have the Mojolicious Framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{MOJO_MODE} = 'development';
#$ENV{MOJO_MODE} = 'production';
$ENV{MOJO_APP} ||= 'MojoCheckbot';

# Start commands
Mojolicious::Commands->start;

